### ISSUE TITLE
tesseract: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by think2011** [matteotiziano/secret-harbor#1]
![](http://s1.momo.moda/2015/06/11/37a749d808e46495a8da1e5352d03cae.png)

**Comment by matteotiziano** [comment]
That is an interesting error, I cannot reproduce it in my application. Anyway I have updated the binaries in the custom Tesseract buildpack to include the missing libraries. Please, try a new deploy and let me know if that solves the issue.

**Comment by think2011** [comment]
i try a new deploy and is a new error:

```
tesseract: error while loading shared libraries: liblzma.so.5: cannot open shared object file: No such file or directory
```

my heroku application build up for a long time,maybe i should build a new application and retry。

**Comment by think2011** [comment]
I build a new application:

```
~ $ tesseract test.jpg ./a
tesseract: /app/vendor/tesseract-ocr/lib/libtiff.so.5: no version information available (required by /app/vendor/tesseract-ocr/lib/liblept.so.4)
Tesseract Open Source OCR Engine v3.03 with Leptonica
```

it still looks like some error, but working now, thanks for your help.😄

**Comment by gbatta** [comment]
Just to confirm think2011's experience: I received the same error. However, when I upgraded to   `cedar-14` on Heroku, everything worked fine, though I did get the same `no version information available` message.

Thanks for creating the buildpack!!
